on:
  - push
  - workflow_dispatch

jobs:
  build_meta:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
      - run: pip install build
      - run: make metadata
      - uses: actions/upload-artifact@v4
        with:
          path: output/kconfigs.json
          name: kconfigs.json
  bundle_configs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: tar -cvf configs.tar community
      - uses: actions/upload-artifact@v4
        with:
          path: configs.tar
          name: configs.tar
  assemble:
    needs:
      - build_meta
      - bundle_configs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: input
      - run: |
          mkdir pub
          mkdir pub/kconfigs
          IN="$(realpath "$PWD/input")"
          pushd pub/kconfigs
          cp "$IN/kconfigs.json" .
          tar -xvf "$IN/configs.tar"
      - uses: actions/upload-pages-artifact@v4
        with:
          path: pub/
  deploy:
    needs:
      - assemble
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment





