on:
  - push
  - workflow_dispatch

jobs:
  build_meta:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
      - run: pip install build
      - run: make metadata
      - uses: actions/upload-artifact@v4
        with:
          path: output/kconfigs.json
          name: kconfigs.json
  bundle_configs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: tar -cvf configs.tar community
      - uses: actions/upload-artifact@v4
        with:
          path: configs.tar
          name: configs.tar
  bundle_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: tar -cvf ../site.tar .
        working-directory: site
      - uses: actions/upload-artifact@v4
        with:
          path: site.tar
          name: site.tar
  assemble:
    needs:
      - build_meta
      - bundle_configs
      - bundle_site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: input
      - run: |
          mkdir pub
          mkdir pub/kconfigs
          tar -xvf "input/site.tar" -C pub
          cp "input/kconfigs.json" pub/kconfigs
          tar -xvf "input/configs.tar" -C pub/kconfigs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: pub/
  deploy:
    needs:
      - assemble
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment





